# Generated by Django 4.2.4 on 2023-08-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0007_alter_profileuser_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuser",
            name="telegramm",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
