# Generated by Django 4.2.4 on 2023-08-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0008_profileuser_telegramm"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuser",
            name="phone",
            field=models.CharField(default=0, help_text="Required.", max_length=30),
            preserve_default=False,
        ),
    ]
