# Generated by Django 4.2.4 on 2023-08-27 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0010_alter_profileuser_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileOperations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tel", models.CharField(max_length=50)),
                ("id_num", models.CharField(max_length=50)),
                ("release_date", models.DateField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="my_app.profileuser",
                    ),
                ),
            ],
        ),
    ]
