# Generated by Django 4.2.4 on 2023-08-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0012_alter_profileoperations_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileoperations",
            name="release_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
