# Generated by Django 4.2.4 on 2023-08-27 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0013_alter_profileoperations_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileoperations",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="my_app.profileuser",
            ),
        ),
    ]
