# Generated by Django 4.2.4 on 2023-08-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0014_alter_profileoperations_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileoperations",
            name="status",
            field=models.ImageField(
                choices=[(0, "Archived"), (1, "Available")], default=2, upload_to=""
            ),
            preserve_default=False,
        ),
    ]
